// ============================================================
// APP PORTFOLIO TRACKER
// Dashboard for managing every app/site being built, with
// per-app social media accounts and a content queue.
// ============================================================

import React, { useState, useEffect, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Plus, ExternalLink, Trash2, ChevronDown, ChevronUp,
  Globe, BarChart2, Share2, FileText, Edit2,
} from "lucide-react";
import {
  getApps, addApp, updateApp, deleteApp,
  getStats, upsertStats,
  getSocialAccounts, addSocialAccount, updateSocialAccount, deleteSocialAccount,
  getContentQueue, addContentQueueItem, updateContentQueueItem, deleteContentQueueItem, markContentPosted,
  getPortfolioSummary,
  APP_STATUS_LABELS, APP_STATUS_COLORS,
  PLATFORM_ICONS, PLATFORM_LABELS,
  type AppRecord, type AppStats, type SocialAccount, type ContentQueueItem,
  type AppStatus, type SocialPlatform, type ContentStatus, type ContentType,
} from "@/lib/appPortfolioStore";
import { ENTITY_NAMES } from "@/lib/businessExpenseStore";

// ─── HELPERS ────────────────────────────────────────────────

const ALL_STATUSES = Object.keys(APP_STATUS_LABELS) as AppStatus[];
const ALL_PLATFORMS = Object.keys(PLATFORM_LABELS) as SocialPlatform[];
const CONTENT_STATUSES: ContentStatus[] = ["idea", "draft", "scheduled", "posted", "archived"];
const CONTENT_STATUS_COLORS: Record<ContentStatus, string> = {
  idea:     "bg-gray-500/20 text-gray-300 border-gray-500/30",
  draft:    "bg-blue-500/20 text-blue-300 border-blue-500/30",
  scheduled:"bg-amber-500/20 text-amber-300 border-amber-500/30",
  posted:   "bg-green-500/20 text-green-300 border-green-500/30",
  archived: "bg-red-500/20 text-red-400 border-red-500/30",
};
const CONTENT_TYPES: ContentType[] = ["post","reel","short","story","video","thread","blog","newsletter","ad","other"];
const ENTITY_OPTIONS = Object.entries(ENTITY_NAMES).map(([id, name]) => ({ id, name }));

function fmt(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}
function fmtNum(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return n.toString();
}

// ─── BLANK FORMS ────────────────────────────────────────────

const BLANK_APP: Omit<AppRecord, "id" | "createdAt" | "updatedAt"> = {
  name: "", slug: "", description: "",
  ownerEntityId: "biz-reese-ventures", ownerEntityName: "Reese Ventures LLC",
  status: "idea", techStack: "", liveUrl: "", repoUrl: "", stagingUrl: "",
  launchDate: null, targetLaunchDate: null, notes: "",
};
const BLANK_SOCIAL: Omit<SocialAccount, "id" | "createdAt" | "updatedAt"> = {
  appId: "", platform: "instagram", handle: "", profileUrl: "",
  followerCount: 0, isActive: false, notes: "",
};
const BLANK_CQ: Omit<ContentQueueItem, "id" | "createdAt" | "updatedAt"> = {
  appId: "", socialAccountId: null, platform: "instagram", contentType: "post",
  title: "", body: "", hashtags: "", mediaUrls: "",
  status: "draft", scheduledAt: null, postedAt: null, isAutoGenerated: false, notes: "",
};

// ─── MAIN COMPONENT ─────────────────────────────────────────

export function AppPortfolioTracker() {
  const [apps, setApps] = useState<AppRecord[]>([]);
  const [selectedAppId, setSelectedAppId] = useState<string | null>(null);
  const [expandedAppId, setExpandedAppId] = useState<string | null>(null);
  const [socialAccounts, setSocialAccounts] = useState<SocialAccount[]>([]);
  const [contentQueue, setContentQueue] = useState<ContentQueueItem[]>([]);
  const [statsMap, setStatsMap] = useState<Record<string, AppStats>>({});

  // Forms
  const [showAppForm, setShowAppForm] = useState(false);
  const [appForm, setAppForm] = useState({ ...BLANK_APP });
  const [editingAppId, setEditingAppId] = useState<string | null>(null);

  const [showSocialForm, setShowSocialForm] = useState(false);
  const [socialForm, setSocialForm] = useState({ ...BLANK_SOCIAL });
  const [editingSocialId, setEditingSocialId] = useState<string | null>(null);

  const [showCqForm, setShowCqForm] = useState(false);
  const [cqForm, setCqForm] = useState({ ...BLANK_CQ });
  const [editingCqId, setEditingCqId] = useState<string | null>(null);

  const [filterStatus, setFilterStatus] = useState<string>("all");
  const [cqFilter, setCqFilter] = useState<string>("all");
  const [message, setMessage] = useState<string | null>(null);

  const refresh = useCallback(() => {
    const allApps = getApps();
    setApps(allApps);
    setSocialAccounts(getSocialAccounts());
    setContentQueue(getContentQueue());
    const sm: Record<string, AppStats> = {};
    for (const a of allApps) {
      const s = getStats(a.id);
      if (s) sm[a.id] = s;
    }
    setStatsMap(sm);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const showMsg = (t: string) => { setMessage(t); setTimeout(() => setMessage(null), 3000); };

  const summary = getPortfolioSummary();

  // ── Filtered views ──────────────────────────────────────
  const filteredApps = apps.filter((a) =>
    filterStatus === "all" || a.status === filterStatus
  );
  const selectedApp = apps.find((a) => a.id === selectedAppId) ?? null;
  const appSocial = selectedApp ? socialAccounts.filter((s) => s.appId === selectedApp.id) : [];
  const appQueue = selectedApp
    ? contentQueue.filter((q) =>
        q.appId === selectedApp.id && (cqFilter === "all" || q.status === cqFilter)
      )
    : [];

  // ── App form handlers ────────────────────────────────────
  const handleAppEntityChange = (entityId: string) => {
    setAppForm((p) => ({ ...p, ownerEntityId: entityId, ownerEntityName: ENTITY_NAMES[entityId] ?? entityId }));
  };
  const handleSaveApp = () => {
    if (!appForm.name.trim()) { showMsg("App name required"); return; }
    const slug = appForm.slug || appForm.name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    if (editingAppId) {
      updateApp(editingAppId, { ...appForm, slug });
      showMsg(`${appForm.name} updated`);
      setEditingAppId(null);
    } else {
      const app = addApp({ ...appForm, slug });
      showMsg(`${app.name} added`);
    }
    setAppForm({ ...BLANK_APP });
    setShowAppForm(false);
    refresh();
  };
  const startEditApp = (a: AppRecord) => {
    setAppForm({ name: a.name, slug: a.slug, description: a.description, ownerEntityId: a.ownerEntityId, ownerEntityName: a.ownerEntityName, status: a.status, techStack: a.techStack, liveUrl: a.liveUrl, repoUrl: a.repoUrl, stagingUrl: a.stagingUrl, launchDate: a.launchDate, targetLaunchDate: a.targetLaunchDate, notes: a.notes });
    setEditingAppId(a.id);
    setShowAppForm(true);
  };
  const handleDeleteApp = (a: AppRecord) => {
    if (!window.confirm(`Delete "${a.name}" and all its social accounts and content?`)) return;
    deleteApp(a.id);
    if (selectedAppId === a.id) setSelectedAppId(null);
    refresh();
    showMsg(`${a.name} deleted`);
  };

  // ── Social form handlers ─────────────────────────────────
  const handleSaveSocial = () => {
    if (!selectedApp) return;
    if (!socialForm.handle.trim()) { showMsg("Handle required"); return; }
    if (editingSocialId) {
      updateSocialAccount(editingSocialId, socialForm);
      showMsg("Account updated");
      setEditingSocialId(null);
    } else {
      addSocialAccount({ ...socialForm, appId: selectedApp.id });
      showMsg("Social account added");
    }
    setSocialForm({ ...BLANK_SOCIAL });
    setShowSocialForm(false);
    refresh();
  };
  const startEditSocial = (s: SocialAccount) => {
    setSocialForm({ appId: s.appId, platform: s.platform, handle: s.handle, profileUrl: s.profileUrl, followerCount: s.followerCount, isActive: s.isActive, notes: s.notes });
    setEditingSocialId(s.id);
    setShowSocialForm(true);
  };

  // ── Content queue handlers ───────────────────────────────
  const handleSaveCq = () => {
    if (!selectedApp) return;
    if (!cqForm.title.trim()) { showMsg("Title required"); return; }
    if (editingCqId) {
      updateContentQueueItem(editingCqId, cqForm);
      showMsg("Content updated");
      setEditingCqId(null);
    } else {
      addContentQueueItem({ ...cqForm, appId: selectedApp.id });
      showMsg("Content added to queue");
    }
    setCqForm({ ...BLANK_CQ });
    setShowCqForm(false);
    refresh();
  };
  const startEditCq = (q: ContentQueueItem) => {
    setCqForm({ appId: q.appId, socialAccountId: q.socialAccountId, platform: q.platform, contentType: q.contentType, title: q.title, body: q.body, hashtags: q.hashtags, mediaUrls: q.mediaUrls, status: q.status, scheduledAt: q.scheduledAt, postedAt: q.postedAt, isAutoGenerated: q.isAutoGenerated, notes: q.notes });
    setEditingCqId(q.id);
    setShowCqForm(true);
  };

  // ── Stats inline editing ─────────────────────────────────
  const handleStatChange = (appId: string, field: keyof Omit<AppStats, "appId" | "updatedAt">, val: string) => {
    const num = parseFloat(val) || 0;
    upsertStats(appId, { [field]: num });
    refresh();
  };

  // ─────────────────────────────────────────────────────────
  // RENDER
  // ─────────────────────────────────────────────────────────
  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h3 className="text-xl font-bold text-white flex items-center gap-2">
          <Globe className="h-5 w-5 text-blue-400" />
          App Portfolio
        </h3>
        <p className="text-sm text-gray-400 mt-1">
          Track every app, site, and product being built — stats, social media, and content queue.
        </p>
      </div>

      {/* Summary strip */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        {[
          { label: "Total Apps", value: summary.totalApps, color: "text-white" },
          { label: "Live", value: summary.byStatus.live, color: "text-green-400" },
          { label: "Building", value: summary.byStatus.building + summary.byStatus.beta, color: "text-amber-400" },
          { label: "Social Accounts", value: `${summary.activeSocialAccounts}/${summary.totalSocialAccounts}`, color: "text-blue-400" },
          { label: "Content Queue", value: summary.contentQueueTotal, color: "text-purple-400" },
        ].map((s) => (
          <Card key={s.label} className="bg-white/5 border-white/10">
            <CardContent className="p-3 text-center">
              <p className={`text-2xl font-bold ${s.color}`}>{s.value}</p>
              <p className="text-xs text-gray-500 mt-0.5">{s.label}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Toast */}
      {message && (
        <div className="fixed bottom-4 right-4 z-50 bg-green-700 text-white text-sm px-4 py-2 rounded-lg shadow-lg">
          {message}
        </div>
      )}

      <Tabs defaultValue="apps">
        <TabsList className="bg-white/5 border border-white/10">
          <TabsTrigger value="apps" className="text-xs">📱 Apps</TabsTrigger>
          <TabsTrigger value="detail" disabled={!selectedApp} className="text-xs">
            {selectedApp ? `⚙️ ${selectedApp.name}` : "⚙️ Select an app"}
          </TabsTrigger>
          <TabsTrigger value="social" disabled={!selectedApp} className="text-xs">📲 Social</TabsTrigger>
          <TabsTrigger value="queue" disabled={!selectedApp} className="text-xs">📅 Content Queue</TabsTrigger>
        </TabsList>

        {/* ── APPS LIST TAB ──────────────────────────────── */}
        <TabsContent value="apps" className="space-y-4 mt-4">
          {/* Filters + Add */}
          <div className="flex items-center gap-3 flex-wrap">
            <Button
              size="sm"
              onClick={() => { setShowAppForm(true); setEditingAppId(null); setAppForm({ ...BLANK_APP }); }}
              className="bg-blue-600 hover:bg-blue-700 text-white text-xs"
            >
              <Plus className="h-3.5 w-3.5 mr-1" /> Add App
            </Button>
            <Select value={filterStatus} onValueChange={setFilterStatus}>
              <SelectTrigger className="w-[140px] h-8 bg-white/5 border-white/10 text-gray-300 text-xs">
                <SelectValue placeholder="All Statuses" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Statuses</SelectItem>
                {ALL_STATUSES.map((s) => (
                  <SelectItem key={s} value={s}>{APP_STATUS_LABELS[s]}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Add/edit app form */}
          {showAppForm && (
            <Card className="bg-white/5 border-white/10">
              <CardHeader className="pb-2">
                <CardTitle className="text-sm text-white">{editingAppId ? "Edit App" : "Add App"}</CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">App Name *</Label>
                    <Input value={appForm.name} onChange={(e) => setAppForm((p) => ({ ...p, name: e.target.value }))} placeholder="e.g. TruthSlayer" className="bg-white/5 border-white/10 text-white text-sm" />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">Owner Entity</Label>
                    <Select value={appForm.ownerEntityId} onValueChange={handleAppEntityChange}>
                      <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {ENTITY_OPTIONS.map((o) => <SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">Status</Label>
                    <Select value={appForm.status} onValueChange={(v) => setAppForm((p) => ({ ...p, status: v as AppStatus }))}>
                      <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                      <SelectContent>
                        {ALL_STATUSES.map((s) => <SelectItem key={s} value={s}>{APP_STATUS_LABELS[s]}</SelectItem>)}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">Tech Stack</Label>
                    <Input value={appForm.techStack} onChange={(e) => setAppForm((p) => ({ ...p, techStack: e.target.value }))} placeholder="React + Supabase..." className="bg-white/5 border-white/10 text-white text-sm" />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">Live URL</Label>
                    <Input value={appForm.liveUrl} onChange={(e) => setAppForm((p) => ({ ...p, liveUrl: e.target.value }))} placeholder="https://..." className="bg-white/5 border-white/10 text-white text-sm" />
                  </div>
                  <div className="space-y-1">
                    <Label className="text-xs text-gray-400">GitHub Repo</Label>
                    <Input value={appForm.repoUrl} onChange={(e) => setAppForm((p) => ({ ...p, repoUrl: e.target.value }))} placeholder="https://github.com/..." className="bg-white/5 border-white/10 text-white text-sm" />
                  </div>
                </div>
                <div className="space-y-1">
                  <Label className="text-xs text-gray-400">Description</Label>
                  <Textarea value={appForm.description} onChange={(e) => setAppForm((p) => ({ ...p, description: e.target.value }))} placeholder="What does this app do?" className="bg-white/5 border-white/10 text-gray-200 text-xs min-h-[60px] resize-none" />
                </div>
                <div className="space-y-1">
                  <Label className="text-xs text-gray-400">Notes / Next Steps</Label>
                  <Textarea value={appForm.notes} onChange={(e) => setAppForm((p) => ({ ...p, notes: e.target.value }))} placeholder="What needs to happen next?" className="bg-white/5 border-white/10 text-gray-200 text-xs min-h-[50px] resize-none" />
                </div>
                <div className="flex gap-2">
                  <Button size="sm" onClick={handleSaveApp} className="bg-blue-600 hover:bg-blue-700 text-white text-xs">{editingAppId ? "Save" : "Add App"}</Button>
                  <Button size="sm" variant="ghost" onClick={() => { setShowAppForm(false); setEditingAppId(null); }} className="text-gray-400 text-xs">Cancel</Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* App cards */}
          <div className="space-y-2">
            {filteredApps.length === 0 && (
              <div className="text-center py-10 text-gray-500 text-sm">No apps match the filter.</div>
            )}
            {filteredApps.map((app) => {
              const stats = statsMap[app.id];
              const social = socialAccounts.filter((s) => s.appId === app.id);
              const isSelected = selectedAppId === app.id;
              return (
                <div
                  key={app.id}
                  className={`rounded-xl border transition ${isSelected ? "border-blue-500/50 bg-blue-500/5" : "border-white/10 bg-white/5"}`}
                >
                  <div className="flex items-center gap-3 p-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="text-sm font-semibold text-white">{app.name}</span>
                        <Badge className={`text-[10px] border ${APP_STATUS_COLORS[app.status]}`}>
                          {APP_STATUS_LABELS[app.status]}
                        </Badge>
                        <span className="text-xs text-gray-500">{ENTITY_NAMES[app.ownerEntityId] ?? app.ownerEntityName}</span>
                      </div>
                      {app.description && <p className="text-xs text-gray-500 truncate mt-0.5">{app.description}</p>}
                      <div className="flex items-center gap-3 mt-1 flex-wrap">
                        {stats && stats.totalUsers > 0 && <span className="text-xs text-gray-400">👤 {fmtNum(stats.totalUsers)} users</span>}
                        {stats && stats.mrr > 0 && <span className="text-xs text-gray-400">💰 {fmt(stats.mrr)}/mo</span>}
                        {social.length > 0 && <span className="text-xs text-gray-400">📲 {social.filter((s) => s.isActive).length}/{social.length} social</span>}
                      </div>
                    </div>
                    <div className="flex items-center gap-1 flex-shrink-0">
                      {app.liveUrl && (
                        <a href={app.liveUrl} target="_blank" rel="noopener noreferrer" className="p-1.5 text-gray-400 hover:text-white">
                          <ExternalLink className="h-3.5 w-3.5" />
                        </a>
                      )}
                      <Button size="sm" variant="ghost" onClick={() => { setSelectedAppId(app.id); }} className={`text-xs ${isSelected ? "text-blue-400" : "text-gray-400 hover:text-white"}`}>
                        {isSelected ? "Selected ✓" : "Select"}
                      </Button>
                      <button onClick={() => startEditApp(app)} className="p-1.5 text-gray-500 hover:text-white text-xs">✎</button>
                      <button onClick={() => handleDeleteApp(app)} className="p-1.5 text-gray-600 hover:text-red-400">
                        <Trash2 className="h-3.5 w-3.5" />
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </TabsContent>

        {/* ── APP DETAIL / STATS TAB ─────────────────────── */}
        <TabsContent value="detail" className="space-y-4 mt-4">
          {selectedApp && (
            <>
              <div className="flex items-start justify-between">
                <div>
                  <h4 className="text-lg font-bold text-white">{selectedApp.name}</h4>
                  <p className="text-xs text-gray-500 mt-0.5">{selectedApp.description}</p>
                </div>
                <Badge className={`text-xs border ${APP_STATUS_COLORS[selectedApp.status]}`}>
                  {APP_STATUS_LABELS[selectedApp.status]}
                </Badge>
              </div>

              {/* Links */}
              <div className="flex gap-2 flex-wrap">
                {selectedApp.liveUrl && <a href={selectedApp.liveUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs text-blue-400 hover:text-blue-300 underline"><Globe className="h-3 w-3" /> Live site</a>}
                {selectedApp.repoUrl && <a href={selectedApp.repoUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs text-gray-400 hover:text-white underline">📁 Repo</a>}
                {selectedApp.stagingUrl && <a href={selectedApp.stagingUrl} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs text-gray-400 hover:text-white underline">🧪 Staging</a>}
              </div>

              {/* Tech + Notes */}
              {selectedApp.techStack && <p className="text-xs text-gray-400">🛠 <span className="text-gray-300">{selectedApp.techStack}</span></p>}
              {selectedApp.notes && (
                <Card className="bg-white/5 border-white/10">
                  <CardContent className="p-3">
                    <p className="text-xs text-gray-400 font-medium mb-1">Next Steps / Notes</p>
                    <p className="text-xs text-gray-300 whitespace-pre-wrap">{selectedApp.notes}</p>
                  </CardContent>
                </Card>
              )}

              {/* Stats editor */}
              <Card className="bg-white/5 border-white/10">
                <CardHeader className="pb-2">
                  <CardTitle className="text-sm text-white flex items-center gap-2">
                    <BarChart2 className="h-4 w-4 text-blue-400" /> Stats
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                    {(["totalUsers","dau","mau","downloads","avgRating","ratingCount","mrr","totalRevenue"] as const).map((field) => {
                      const labels: Record<string, string> = {
                        totalUsers: "Total Users", dau: "DAU", mau: "MAU", downloads: "Downloads",
                        avgRating: "Avg Rating", ratingCount: "# Ratings", mrr: "MRR ($)", totalRevenue: "Total Revenue ($)",
                      };
                      return (
                        <div key={field} className="space-y-1">
                          <Label className="text-[10px] text-gray-500">{labels[field]}</Label>
                          <Input
                            type="number"
                            min={0}
                            step={field === "avgRating" ? 0.1 : 1}
                            value={statsMap[selectedApp.id]?.[field] ?? 0}
                            onChange={(e) => handleStatChange(selectedApp.id, field, e.target.value)}
                            className="bg-white/5 border-white/10 text-white text-sm h-8"
                          />
                        </div>
                      );
                    })}
                  </div>
                </CardContent>
              </Card>
            </>
          )}
        </TabsContent>

        {/* ── SOCIAL MEDIA TAB ───────────────────────────── */}
        <TabsContent value="social" className="space-y-4 mt-4">
          {selectedApp && (
            <>
              <div className="flex items-center justify-between">
                <h4 className="text-sm font-semibold text-white flex items-center gap-2">
                  <Share2 className="h-4 w-4 text-pink-400" />
                  Social Accounts — {selectedApp.name}
                </h4>
                <Button
                  size="sm"
                  onClick={() => { setShowSocialForm(true); setEditingSocialId(null); setSocialForm({ ...BLANK_SOCIAL, appId: selectedApp.id }); }}
                  className="bg-pink-600/80 hover:bg-pink-600 text-white text-xs"
                >
                  <Plus className="h-3.5 w-3.5 mr-1" /> Add Account
                </Button>
              </div>

              {/* Social add/edit form */}
              {showSocialForm && (
                <Card className="bg-white/5 border-white/10">
                  <CardContent className="p-4 space-y-3">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Platform</Label>
                        <Select value={socialForm.platform} onValueChange={(v) => setSocialForm((p) => ({ ...p, platform: v as SocialPlatform }))}>
                          <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                          <SelectContent>
                            {ALL_PLATFORMS.map((pl) => (
                              <SelectItem key={pl} value={pl}>{PLATFORM_ICONS[pl]} {PLATFORM_LABELS[pl]}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Handle / Channel Name</Label>
                        <Input value={socialForm.handle} onChange={(e) => setSocialForm((p) => ({ ...p, handle: e.target.value }))} placeholder="@handle" className="bg-white/5 border-white/10 text-white text-sm" />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Profile URL</Label>
                        <Input value={socialForm.profileUrl} onChange={(e) => setSocialForm((p) => ({ ...p, profileUrl: e.target.value }))} placeholder="https://..." className="bg-white/5 border-white/10 text-white text-sm" />
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Followers</Label>
                        <Input type="number" min={0} value={socialForm.followerCount} onChange={(e) => setSocialForm((p) => ({ ...p, followerCount: parseInt(e.target.value) || 0 }))} className="bg-white/5 border-white/10 text-white text-sm" />
                      </div>
                    </div>
                    <label className="flex items-center gap-2 text-xs text-gray-400 cursor-pointer">
                      <input type="checkbox" checked={socialForm.isActive} onChange={(e) => setSocialForm((p) => ({ ...p, isActive: e.target.checked }))} className="accent-pink-500" />
                      Account is active
                    </label>
                    <Input value={socialForm.notes} onChange={(e) => setSocialForm((p) => ({ ...p, notes: e.target.value }))} placeholder="Notes (e.g. needs bio update)" className="bg-white/5 border-white/10 text-white text-sm" />
                    <div className="flex gap-2">
                      <Button size="sm" onClick={handleSaveSocial} className="bg-pink-600/80 hover:bg-pink-600 text-white text-xs">{editingSocialId ? "Save" : "Add"}</Button>
                      <Button size="sm" variant="ghost" onClick={() => { setShowSocialForm(false); setEditingSocialId(null); }} className="text-gray-400 text-xs">Cancel</Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Social account list */}
              {appSocial.length === 0 ? (
                <p className="text-sm text-gray-500 py-4 text-center">No social accounts yet. Add one above.</p>
              ) : (
                <div className="space-y-2">
                  {appSocial.map((acc) => (
                    <div key={acc.id} className={`flex items-center gap-3 p-3 rounded-lg border transition ${acc.isActive ? "border-white/10 bg-white/5" : "border-white/5 bg-white/[0.02] opacity-60"}`}>
                      <span className="text-2xl flex-shrink-0">{PLATFORM_ICONS[acc.platform]}</span>
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="text-sm font-medium text-white">{acc.handle}</span>
                          <span className="text-xs text-gray-500">{PLATFORM_LABELS[acc.platform]}</span>
                          {!acc.isActive && <Badge className="text-[10px] bg-gray-500/20 text-gray-400 border-gray-500/30 border">not set up</Badge>}
                        </div>
                        <div className="flex items-center gap-3 mt-0.5">
                          {acc.followerCount > 0 && <span className="text-xs text-gray-400">{fmtNum(acc.followerCount)} followers</span>}
                          {acc.notes && <span className="text-xs text-gray-500 truncate">{acc.notes}</span>}
                        </div>
                      </div>
                      <div className="flex items-center gap-1 flex-shrink-0">
                        {acc.profileUrl && <a href={acc.profileUrl} target="_blank" rel="noopener noreferrer" className="p-1.5 text-gray-400 hover:text-white"><ExternalLink className="h-3.5 w-3.5" /></a>}
                        <button onClick={() => { updateSocialAccount(acc.id, { isActive: !acc.isActive }); refresh(); }} className="p-1.5 text-xs text-gray-400 hover:text-white" title={acc.isActive ? "Mark inactive" : "Mark active"}>
                          {acc.isActive ? "✅" : "⭕"}
                        </button>
                        <button onClick={() => startEditSocial(acc)} className="p-1.5 text-xs text-gray-400 hover:text-white">✎</button>
                        <button onClick={() => { deleteSocialAccount(acc.id); refresh(); showMsg("Account removed"); }} className="p-1.5 text-gray-600 hover:text-red-400"><Trash2 className="h-3.5 w-3.5" /></button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}
        </TabsContent>

        {/* ── CONTENT QUEUE TAB ──────────────────────────── */}
        <TabsContent value="queue" className="space-y-4 mt-4">
          {selectedApp && (
            <>
              <div className="flex items-center justify-between flex-wrap gap-2">
                <h4 className="text-sm font-semibold text-white flex items-center gap-2">
                  <FileText className="h-4 w-4 text-purple-400" />
                  Content Queue — {selectedApp.name}
                </h4>
                <div className="flex items-center gap-2">
                  <Select value={cqFilter} onValueChange={setCqFilter}>
                    <SelectTrigger className="w-[120px] h-8 bg-white/5 border-white/10 text-gray-300 text-xs"><SelectValue /></SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all">All</SelectItem>
                      {CONTENT_STATUSES.map((s) => <SelectItem key={s} value={s} className="capitalize">{s}</SelectItem>)}
                    </SelectContent>
                  </Select>
                  <Button size="sm" onClick={() => { setShowCqForm(true); setEditingCqId(null); setCqForm({ ...BLANK_CQ, appId: selectedApp.id, platform: appSocial[0]?.platform ?? "instagram", socialAccountId: appSocial[0]?.id ?? null }); }} className="bg-purple-600/80 hover:bg-purple-600 text-white text-xs">
                    <Plus className="h-3.5 w-3.5 mr-1" /> Add Content
                  </Button>
                </div>
              </div>

              {/* Content add/edit form */}
              {showCqForm && (
                <Card className="bg-white/5 border-white/10">
                  <CardContent className="p-4 space-y-3">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Platform</Label>
                        <Select value={cqForm.platform} onValueChange={(v) => setCqForm((p) => ({ ...p, platform: v as SocialPlatform }))}>
                          <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                          <SelectContent>
                            {ALL_PLATFORMS.map((pl) => <SelectItem key={pl} value={pl}>{PLATFORM_ICONS[pl]} {PLATFORM_LABELS[pl]}</SelectItem>)}
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Content Type</Label>
                        <Select value={cqForm.contentType} onValueChange={(v) => setCqForm((p) => ({ ...p, contentType: v as ContentType }))}>
                          <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                          <SelectContent>
                            {CONTENT_TYPES.map((t) => <SelectItem key={t} value={t} className="capitalize">{t}</SelectItem>)}
                          </SelectContent>
                        </Select>
                      </div>
                      <div className="space-y-1">
                        <Label className="text-xs text-gray-400">Status</Label>
                        <Select value={cqForm.status} onValueChange={(v) => setCqForm((p) => ({ ...p, status: v as ContentStatus }))}>
                          <SelectTrigger className="bg-white/5 border-white/10 text-gray-200 text-sm h-9"><SelectValue /></SelectTrigger>
                          <SelectContent>
                            {CONTENT_STATUSES.map((s) => <SelectItem key={s} value={s} className="capitalize">{s}</SelectItem>)}
                          </SelectContent>
                        </Select>
                      </div>
                    </div>
                    <div className="space-y-1">
                      <Label className="text-xs text-gray-400">Title / Caption *</Label>
                      <Input value={cqForm.title} onChange={(e) => setCqForm((p) => ({ ...p, title: e.target.value }))} placeholder="Post title or first line of caption..." className="bg-white/5 border-white/10 text-white text-sm" />
                    </div>
                    <div className="space-y-1">
                      <Label className="text-xs text-gray-400">Body</Label>
                      <Textarea value={cqForm.body} onChange={(e) => setCqForm((p) => ({ ...p, body: e.target.value }))} placeholder="Full caption / post body..." className="bg-white/5 border-white/10 text-gray-200 text-xs min-h-[70px] resize-none" />
                    </div>
                    <div className="space-y-1">
                      <Label className="text-xs text-gray-400">Hashtags</Label>
                      <Input value={cqForm.hashtags} onChange={(e) => setCqForm((p) => ({ ...p, hashtags: e.target.value }))} placeholder="#tag1 #tag2 #tag3" className="bg-white/5 border-white/10 text-white text-sm" />
                    </div>
                    <div className="flex gap-2">
                      <Button size="sm" onClick={handleSaveCq} className="bg-purple-600/80 hover:bg-purple-600 text-white text-xs">{editingCqId ? "Save" : "Add to Queue"}</Button>
                      <Button size="sm" variant="ghost" onClick={() => { setShowCqForm(false); setEditingCqId(null); }} className="text-gray-400 text-xs">Cancel</Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Content queue list */}
              {appQueue.length === 0 ? (
                <p className="text-sm text-gray-500 py-4 text-center">No content in queue. Add some above.</p>
              ) : (
                <div className="space-y-2">
                  {appQueue.map((item) => (
                    <div key={item.id} className="p-3 rounded-lg border border-white/10 bg-white/5">
                      <div className="flex items-start justify-between gap-2">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="text-sm font-medium text-white truncate">{item.title}</span>
                            <Badge className={`text-[10px] border ${CONTENT_STATUS_COLORS[item.status]}`}>{item.status}</Badge>
                            <span className="text-[10px] text-gray-500">{PLATFORM_ICONS[item.platform]} {item.contentType}</span>
                            {item.isAutoGenerated && <Badge className="text-[10px] bg-blue-500/20 text-blue-300 border-blue-500/30 border">auto</Badge>}
                          </div>
                          {item.body && <p className="text-xs text-gray-400 mt-1 line-clamp-2">{item.body}</p>}
                          {item.hashtags && <p className="text-xs text-blue-400/70 mt-0.5 truncate">{item.hashtags}</p>}
                          {item.scheduledAt && <p className="text-xs text-amber-400 mt-0.5">📅 Scheduled: {new Date(item.scheduledAt).toLocaleDateString()}</p>}
                          {item.postedAt && <p className="text-xs text-green-400 mt-0.5">✅ Posted: {new Date(item.postedAt).toLocaleDateString()}</p>}
                        </div>
                        <div className="flex items-center gap-1 flex-shrink-0">
                          {item.status !== "posted" && (
                            <button
                              onClick={() => { markContentPosted(item.id); refresh(); showMsg("Marked as posted!"); }}
                              className="text-xs text-green-400 hover:text-green-300 px-2 py-1 rounded border border-green-500/30 bg-green-500/10"
                              title="Mark as posted"
                            >
                              ✓ Post
                            </button>
                          )}
                          <button onClick={() => startEditCq(item)} className="p-1.5 text-xs text-gray-400 hover:text-white">✎</button>
                          <button onClick={() => { deleteContentQueueItem(item.id); refresh(); showMsg("Deleted"); }} className="p-1.5 text-gray-600 hover:text-red-400">
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
}
